#!/bin/bash

# homebrew_check=$(which brew)
pkgconfig_check=$(which pkg-config)
qemu_check=$(which qemu-img)
qemuVer_check=$(qemu-img --v | grep 1.5.0)
current_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
vm_dir="${current_dir}/work/vm"
image_dir="${current_dir}/image/ece391.qcow"
kernel_dir="${current_dir}/work/source/linux-2.6.22.5/bzImage"

# if [ "${homebrew_check}" == "" ]; then
#     echo "brew is not installed"
#     ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
# fi

if [ "${pkgconfig_check}" == "" ]; then
    echo "install pkg-config"
    brew install pkg-config
fi

if [ "${qemu_check}" == "" ]; then #qemu not installed
    cd "${current_dir}/qemu_mac"
    ./configure
    make
    sudo make install
else
    if [ "${qemuVer_check}" == "" ]; then
        echo "Wrong version of qemu is installed"
        echo "Please uninstall it , then run this script again"
        exit 1
    fi
fi

rm -rf "${vm_dir}"
mkdir -p "${vm_dir}"
qemu-img create -b "${image_dir}" -f qcow2 "${vm_dir}/devel.qcow"
qemu-img create -b "${image_dir}" -f qcow2 "${vm_dir}/test.qcow"

printf "#!/bin/bash \n qemu-system-i386 -hda \"${vm_dir}/devel.qcow\" -m 512 -name devel" > ~/Desktop/devel
printf "#!/bin/bash \n qemu-system-i386 -hda \"${vm_dir}/test.qcow\" -m 512 -name test -gdb tcp:127.0.0.1:1234 -S -kernel \"${kernel_dir}\"" > ~/Desktop/test_debug
printf "#!/bin/bash \n qemu-system-i386 -hda \"${vm_dir}/test.qcow\" -m 512 -name test -kernel \"${kernel_dir}\"" > ~/Desktop/test_nodebug

chmod a+x ~/Desktop/devel ~/Desktop/test_debug ~/Desktop/test_nodebug
