#!/bin/bash

echo '################################################################'
echo '#                                                              #'
echo '#            ECE391 Localized Development Environment          #'
echo '#                                                              #'
echo '#                     Created by DukeGaGa                      #'
echo '#                                                              #'
echo '#                          2015.08.27                          #'
echo '#                                                              #'
echo '################################################################'

homebrew_check=$(which brew)
pkgconfig_check=$(which pkg-config)
qemu_check=$(which qemu-img)
current_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
vm_dir="${current_dir}/work/vm"
image_dir="${current_dir}/image/ece391.qcow"
kernel_dir="${current_dir}/work/source/linux-2.6.22.5/bzImage"

if [ "${homebrew_check}" == "" ]; then
    echo "Installing homebrew..."
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

if [ "${pkgconfig_check}" == "" ]; then
    echo "Installing pkg-config..."
    brew install pkg-config
fi

if [ "${qemu_check}" == "" ]; then
    echo "Compiling qemu..."
    brew install glib
    brew install pixman
    cd "${current_dir}/qemu_mac"
    ./configure
    make
    echo "Installing qemu..."
    sudo make install
else
    qemu_ver_check=$(qemu-img --v | grep 1.5.0)
    if [ "${qemu_ver_check}" == "" ]; then
        echo "Wrong version of qemu is installed"
        echo "Please uninstall it, then run this script again"
        exit 1
    fi
fi

if [ ! -d "${vm_dir}" ]; then
    mkdir -p "${vm_dir}"
fi

if [ ! -f "${vm_dir}/devel.qcow" ]; then
    qemu-img create -b "${image_dir}" -f qcow2 "${vm_dir}/devel.qcow"
fi

if [ ! -f "${vm_dir}/test.qcow" ]; then
    qemu-img create -b "${image_dir}" -f qcow2 "${vm_dir}/test.qcow"
fi

echo "qemu-system-i386 -hda \"${vm_dir}/devel.qcow\" -m 512 -name devel" > ~/Desktop/devel
echo "qemu-system-i386 -hda \"${vm_dir}/test.qcow\" -m 512 -name test -gdb tcp:127.0.0.1:1234 -S -kernel \"${kernel_dir}\"" > ~/Desktop/test_debug
echo "qemu-system-i386 -hda \"${vm_dir}/test.qcow\" -m 512 -name test -kernel \"${kernel_dir}\"" > ~/Desktop/test_nodebug

chmod a+x ~/Desktop/devel ~/Desktop/test_debug ~/Desktop/test_nodebug
