#!/bin/bash

echo "Starting qemu vm..."
echo "qemu-system-i386 -hda ~/Documents/ece391/work/vm/devel.qcow -m 768 -name devel -redir tcp:2222::22"
qemu-system-i386 -hda ~/Documents/ece391/work/vm/devel.qcow -m 768 -name devel -redir tcp:2222::22 &


sleep 1

ssh -p 2222 user@localhost

echo "Shutting down qemu vm..."

sleep 30
pkill qemu-system-i386

echo "Done! Qemu vm closed."

