#!/bin/bash


echo "Welcome to ece391 setup for OS X"
echo "Yifei Teng, Yu Wang, Han Yan, Brett Jackson"
echo "Special Thanks for our TA Fei Deng"
homebrew_check=$(which brew)
wget_check=$(which wget)
userdir=$(cd ~ ;pwd)


if [ "${homebrew_check}" == "" ]; then
    echo "Installing homebrew..."
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

if [ "${wget_check}" == "" ]; then
    brew install wget
fi

# download the main img

if [ ! -f "ece391.tar.gz" ];then
    wget "http://duke8253.net/ece391/ece391.tar.gz"
fi
if [ ! -d "ece391" ]; then
    tar xzvf ece391.tar.gz
    echo "Unzip finished"
else
    echo "Folder ece391 already exists"
fi
cp setup_mac ./ece391/setup_mac
cd ece391
./setup_mac #setup for mac
cd ../
./unisonSync #setup for unison


# create shortcut command
echo '#!/bin/bash' > /usr/local/bin/ece391.test
echo "qemu-system-i386 -hda work/vm/test.qcow -no-kvm -kernel ~/ece391ForMac/ece391/work/source/linux-2.6.22.5/bzImage -m 512 -gdb tcp:127.0.0.1:1234 -S -name test" >> /usr/local/bin/ece391.test
echo '#!/bin/bash' > /usr/local/bin/ece391.dev
echo "qemu-system-i386 -hda ~/ece391ForMac/ece391/work/vm/devel.qcow -net nic -net user,smb=${userdir}/ece391ForMac/ece391/work -m 768 -name devel -redir tcp:2222::22" >> /usr/local/bin/ece391.dev
echo '#!/bin/bash' > /usr/local/bin/ece391.ssh
echo "ssh -p 2222 user@localhost" >> /usr/local/bin/ece391.ssh

chmod a+x /usr/local/bin/ece391.test /usr/local/bin/ece391.dev /usr/local/bin/ece391.ssh

# end create shortcut
