#!/bin/bash


echo "Welcome to ece391 setup for OS X"
echo "Yifei Teng, Yu Wang, Han Yan, Brett Jackson"
echo "Special Thanks for our TA Fei Deng"
homebrew_check=$(which brew)
p7zip_check=$(which 7z)
wget_check=$(which wget)

if [ "${homebrew_check}" == "" ]; then
    echo "Installing homebrew..."
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

if [ "${p7zip_check}" == "" ]; then
    brew install p7zip
fi

if [ "${wget_check}" == "" ]; then
    brew install wget
fi

# download the main img

if [ ! -f "ece391_sp15.zip" ];then
    wget "http://duke8253.net/ece391/ece391_sp15.zip"
fi
7z x ece391_sp15.zip
echo "Unzip finished"

cp setup_mac ./ece391/setup_mac
cd ece391
rm ./*.bat
rm ./*.msi
rm -r qemu
wget "http://duke8253.net/ece391/qemu_mac.zip"
7z x qemu_mac.zip
./setup_mac
