#!/bin/bash

cd ~/ece391ForMac
echo  "Mounting Shared Volumes..."
./mount391

userdir=$(cd ~ ;pwd)
MY_PATH="`dirname \"$0\"`"              # relative
MY_PATH="`( cd \"${MY_PATH}\" && pwd )`"  # absolutized and normalized
if [ -z "${MY_PATH}" ] ; then
  echo "error; for some reason, the path is not accessible"
  echo "to the script (e.g. permissions re-evaled after suid)"
  exit 1  # fail
fi

dev_old_path=$("${MY_PATH}"/cowhacker/cowhacker patch "${userdir}"/ece391ForMac/ece391/work/vm/devel.qcow)
test_old_path=$("${MY_PATH}"/cowhacker/cowhacker patch "${userdir}"/ece391ForMac/ece391/image/ece391.qcow)

unison ~/ece391_Team/ ~/ece391ForMac/ece391/work/ -fat
"${MY_PATH}"/cowhacker/cowhacker revert "${userdir}"/ece391ForMac/ece391/work/vm/devel.qcow "$dev_old_path"
"${MY_PATH}"/cowhacker/cowhacker revert "${userdir}"/ece391ForMac/ece391/work/vm/test.qcow "$test_old_path"

cd ~/ece391ForMac
echo  "Unmounting Shared Volumes..."
./unmount391
