#!/bin/bash

userdir=$(cd ~ ;pwd)
MY_PATH="`dirname \"$0\"`"              # relative
MY_PATH="`( cd \"${MY_PATH}\" && pwd )`"  # absolutized and normalized
if [ -z "${MY_PATH}" ] ; then
  echo "error; for some reason, the path is not accessible"
  echo "to the script (e.g. permissions re-evaled after suid)"
  exit 1  # fail
fi

old_path=$("${MY_PATH}"/ece391ForMac/cowhacker/cowhacker patch "${userdir}"/ece391/work/vm/devel.qcow)
unison ~/ece391_Team/ ~/ece391ForMac/ece391/work/ -fat
"${MY_PATH}"/ece391ForMac/cowhacker/cowhacker revert "${userdir}"/ece391/work/vm/devel.qcow "$old_path"
